### ISSUE TITLE
Camera permissions issue

### ISSUE THREAD

**Issue by dixidroid** [uploadcare/uploadcare-android#9] opened 2019-02-08 14:47 UTC
Missed ability to check camera permissions for Android >= 5

**Comment by dmitry-mukhin** [comment] 2019-02-08 16:45
We're currently rewriting Android app, most likely, the current version of the library will not be fixed.

**Comment by raphaelnew** [comment] 2019-02-09 20:07
Issue is not related to permissions (we do not use any of permissions for Camera etc.) Duplicate of #6

**Closed** 2019-02-10 05:49 UTC
